name: arm64ec

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'bylaws/wine'
        ref: 'upstream-arm64ec'

    - name: install dependencies
      run: |
       sudo apt update
       sudo apt install -y \
       debhelper-compat=13 \
       gcc-mingw-w64 \
       libz-mingw-w64-dev \
       lzma \
       flex \
       bison \
       quilt \
       unzip \
       gettext \
       icoutils \
       sharutils \
       pkg-config \
       dctrl-tools \
       imagemagick \
       librsvg2-bin \
       fontforge-nox \
       khronos-api \
       unicode-data \
       unicode-idna \
       libgl-dev \
       libxi-dev \
       libxt-dev \
       libxmu-dev \
       libx11-dev \
       libxi-dev \
       libxinerama-dev \
       libxcursor-dev \
       libxext-dev \
       libxfixes-dev \
       libxrandr-dev \
       libxcursor-dev \
       libxrender-dev \
       libxkbfile-dev \
       libxxf86vm-dev \
       libxxf86dga-dev \
       libxinerama-dev \
       libglu1-mesa-dev \
       libxcomposite-dev \
       libxkbregistry-dev \
       libxml-libxml-perl \
       libssl-dev \
       libv4l-dev \
       libsdl2-dev \
       libkrb5-dev \
       libudev-dev \
       libpulse-dev \
       libldap2-dev \
       unixodbc-dev \
       libcups2-dev \
       libcapi20-dev \
       libvulkan-dev \
       libopenal-dev \
       libdbus-1-dev \
       freeglut3-dev \
       libunwind-dev \
       libpcap0.8-dev \
       libasound2-dev \
       libgphoto2-dev \
       libosmesa6-dev \
       libncurses-dev \
       libwayland-dev \
       libfreetype-dev \
       libgnutls28-dev \
       libpcsclite-dev \
       libusb-1.0-0-dev \
       libgettextpo-dev \
       libfontconfig-dev \
       ocl-icd-opencl-dev \
       libgstreamer-plugins-base1.0-dev \
       libdrm2 \
       libdrm-dev \
       build-essential
      
    - name: compile wine
      run: |
       wget https://github.com/bylaws/llvm-mingw/releases/download/20240929/llvm-mingw-20240929-ucrt-ubuntu-20.04-aarch64.tar.xz
       tar xf llvm-mingw-20240929-ucrt-ubuntu-20.04-aarch64.tar.xz
       pwd
       ls -R ./llvm-mingw-20240929-ucrt-ubuntu-20.04-aarch64
       export PATH="</home/runner/work/wine/wine/llvm-mingw-20240929-ucrt-ubuntu-20.04-aarch64>/bin:$PATH"
       ./configure --enable-archs=arm64ec,aarch64,i386 --prefix=/usr --with-mingw=clang --disable-tests
       make -j$(nproc)

    - name: tar build folder
      if: always()
      run: |
       cd build
       ls -R
       cd ..
       tar cf build.tar build/
       ls

    - name: Upload build folder
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: build.tar
       path: ./build.tar
