name: arm64ec

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: | 
       sudo dpkg --add-architecture i386 
       sudo apt update 
       sudo apt-get install -y gcc-multilib g++-multilib libdrm-dev libdrm-dev:i386 \
            libx11-dev:i386 libfreetype6-dev:i386 libgl1-mesa-dev:i386 \
            libxext-dev:i386 libxrandr-dev:i386 libxi-dev:i386 libxcursor-dev:i386 \
            libxinerama-dev:i386 libxxf86vm-dev:i386 libxrender-dev:i386 \
            libdbus-1-dev:i386 libfontconfig1-dev:i386
            
    - name: prepare imagefs
      run: |
        mkdir imagefs
        cd imagefs
        pwd
        wget https://github.com/Pipetto-crypto/winlator/raw/refs/heads/dev/app/src/main/assets/imagefs.txz
        tar xf imagefs.txz
        rm -rf imagefs.txz
        sudo chown -R $(whoami):$(whoami) .
        ls ./bin
        ls -l ./bin/gzip

    - name: install Toolchain
      run: |
       wget https://github.com/bylaws/llvm-mingw/releases/download/20250305/llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
       tar -xf llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
       sudo mv llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64 /opt/llvm-mingw

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: ndk
      with:
       ndk-version: r27c
       add-to-path: false
       link-to-sdk: true

    - name: Show SDK and NDK locations
      run: |
       echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
       echo "NDK path=${{ steps.ndk.outputs.ndk-path }}"
       ls /usr/local/lib/android/sdk/ndk
       
    - name: run autogen.sh
      run: ./autogen.sh
      
    - name: compile glibc proton for wine-tools
      run: |
       mkdir wine-tools
       cd wine-tools
       CC=i686-w64-mingw32-gcc ../configure
       make
       
    - name: compile proton arm64ec
      run: |
       mkdir build
       cd build
       DEPS=/home/runner/work/wine/wine/imagefs/data/data/com.winlator.cmod/files/imagefs/usr ARCH="aarch64" WINARCH="arm64ec" ../build.sh --configure --build --compress
