name: arm64ec

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: prepare imagefs
      run: |
        mkdir imagefs
        cd imagefs
        pwd
        wget https://github.com/Pipetto-crypto/winlator/raw/refs/heads/dev/app/src/main/assets/imagefs.txz
        tar xf imagefs.txz
        rm -rf imagefs.txz
        sudo chown -R $(whoami):$(whoami) .
        ls ./bin
        ls -l ./bin/gzip

    - name: install Toolchain
      run: |
       wget https://github.com/bylaws/llvm-mingw/releases/download/20250305/llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
       tar -xf llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
       sudo mv llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64 /opt/llvm-mingw

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: ndk
      with:
       ndk-version: r27c
       add-to-path: false
       link-to-sdk: true

    - name: Show SDK and NDK locations
      run: |
       echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
       echo "NDK path=${{ steps.ndk.outputs.ndk-path }}"
       ls -R /usr/local/lib/android/sdk
       
    - name: compile proton
      run: |
       ./autogen.sh
       mkdir build
       cd build
       DEPS=/home/runner/work/wine/wine/imagefs/data/data/com.winlator.cmod/files/imagefs/usr ARCH="aarch64" WINARCH="arm64ec" ../build.sh --configure --build --compress
