name: arm64ec

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
       sudo apt update
       sudo apt install -y \
       debhelper-compat=13 \
       gcc-mingw-w64 \
       libz-mingw-w64-dev \
       lzma \
       flex \
       bison \
       quilt \
       unzip \
       gettext \
       icoutils \
       sharutils \
       pkg-config \
       dctrl-tools \
       imagemagick \
       librsvg2-bin \
       fontforge-nox \
       khronos-api \
       unicode-data \
       libgl-dev \
       libxi-dev \
       libxt-dev \
       libxmu-dev \
       libx11-dev \
       libxi-dev \
       libxinerama-dev \
       libxcursor-dev \
       libxext-dev \
       libxfixes-dev \
       libxrandr-dev \
       libxcursor-dev \
       libxrender-dev \
       libxkbfile-dev \
       libxxf86vm-dev \
       libxxf86dga-dev \
       libxinerama-dev \
       libglu1-mesa-dev \
       libxcomposite-dev \
       libxkbregistry-dev \
       libxml-libxml-perl \
       libssl-dev \
       libv4l-dev \
       libsdl2-dev \
       libkrb5-dev \
       libudev-dev \
       libpulse-dev \
       libldap2-dev \
       unixodbc-dev \
       libcups2-dev \
       libcapi20-dev \
       libvulkan-dev \
       libopenal-dev \
       libdbus-1-dev \
       freeglut3-dev \
       libunwind-dev \
       libpcap0.8-dev \
       libasound2-dev \
       libgphoto2-dev \
       libosmesa6-dev \
       libncurses-dev \
       libwayland-dev \
       libfreetype-dev \
       libgnutls28-dev \
       libpcsclite-dev \
       libusb-1.0-0-dev \
       libgettextpo-dev \
       libfontconfig-dev \
       ocl-icd-opencl-dev \
       libgstreamer-plugins-base1.0-dev \
       libdrm2 \
       libdrm-dev \
       build-essential
      
    - name: Install Clang 20
      run: |
       wget https://apt.llvm.org/llvm.sh
       chmod +x llvm.sh
       sudo ./llvm.sh 20
       sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
       sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100
       ls /usr/bin
       clang --version
       
    - name: install Toolchain
      run: |
       wget https://github.com/mstorsjo/llvm-mingw/releases/download/20250730/llvm-mingw-20250730-ucrt-ubuntu-22.04-aarch64.tar.xz
       tar xf llvm-mingw-20250730-ucrt-ubuntu-22.04-aarch64.tar.xz
       sudo mv llvm-mingw-20250730-ucrt-ubuntu-22.04-aarch64 /opt/llvm-mingw
       cd /opt/llvm-mingw
       ls
       sudo chown -R $(whoami):$(whoami) .
       
    - name: run autogen.sh
      run: ./autogen.sh
      
    - name: compile proton
      run: |
       export PATH="/opt/llvm-mingw/bin:$PATH"
       ./configure --enable-archs=arm64ec,aarch64,i386 --prefix=/usr --with-mingw=clang --disable-tests
       make -j$(nproc)
       mkdir ./Wine-Build
       sudo make install -j$(nproc) DESTDIR=./Wine-Build
       
    - name: Tar Wine
      run: tar cf Wine-Build.tar Wine-Build/

    - name: Upload wine
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: wine-build.tar.xz
       path: ./Wine-Build.tar
