name: arm64ec

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: prepare imagefs
      run: |
        mkdir imagefs
        cd imagefs
        pwd
        wget https://github.com/Pipetto-crypto/winlator/raw/refs/heads/dev/app/src/main/assets/imagefs.txz
        tar xf imagefs.txz
        rm -rf imagefs.txz
        sudo chown -R $(whoami):$(whoami) .

    - name: compile proton
      run: |
       ./autogen.sh
       mkdir build
       cd build
       DEPS=/home/runner/work/wine/wine/imagefs/data/data/com.winlator.cmod/files/imagefs/usr ARCH="aarch64" WINARCH="arm64ec" ../build.sh --configure --build --compress
