name: arm64ec

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
       sudo dpkg --add-architecture i386
       sudo apt update
       sudo apt install -y --no-install-recommends \
       gcc-multilib g++-multilib build-essential flex bison libtool \
       make cmake nasm yasm autoconf automake gettext pkg-config \
       libx11-dev libx11-dev:i386 libfreetype6-dev libfreetype6-dev:i386 \
       libgl1-mesa-dev libgl1-mesa-dev:i386 libglu1-mesa-dev libglu1-mesa-dev:i386 \
       libxext-dev libxext-dev:i386 libxrandr-dev libxrandr-dev:i386 \
       libxi-dev libxi-dev:i386 libxcursor-dev libxcursor-dev:i386 \
       libxinerama-dev libxinerama-dev:i386 libxxf86vm-dev libxxf86vm-dev:i386 \
       libxrender-dev libxrender-dev:i386 libxcomposite-dev libxcomposite-dev:i386 \
       libfontconfig1-dev libfontconfig1-dev:i386 libdbus-1-dev libdbus-1-dev:i386 \
       libdrm-dev libdrm-dev:i386 libasound2-dev libasound2-dev:i386 \
       libpulse-dev libpulse-dev:i386 \
       zlib1g-dev zlib1g-dev:i386 libpng-dev libpng-dev:i386 \
       libudev-dev libudev-dev:i386
            
    - name: prepare imagefs
      run: |
        mkdir imagefs
        cd imagefs
        pwd
        wget https://github.com/Pipetto-crypto/winlator/raw/refs/heads/dev/app/src/main/assets/imagefs.txz
        tar xf imagefs.txz
        rm -rf imagefs.txz
        sudo chown -R $(whoami):$(whoami) .
        ls ./bin
        ls -l ./bin/gzip

    - name: install Toolchain
      run: |
       wget https://github.com/bylaws/llvm-mingw/releases/download/20250305/llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
       tar -xf llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
       sudo mv llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64 /opt/llvm-mingw

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup NDK
      uses: nttld/setup-ndk@v1
      id: ndk
      with:
       ndk-version: r27c
       add-to-path: false
       link-to-sdk: true

    - name: Show SDK and NDK locations
      run: |
       echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
       echo "NDK path=${{ steps.ndk.outputs.ndk-path }}"
       ls /usr/local/lib/android/sdk/ndk
       
    - name: run autogen.sh
      run: ./autogen.sh
      
    - name: compile glibc proton for wine-tools
      run: |
       mkdir wine-tools
       cd wine-tools
       ../configure --enable-win64 --disable-tests --enable-vulkan --without-capi --without-coreaudio --without-gettext --with-gettextpo=no --without-gphoto --without-inotify --without-netapi --without-opencl --without-oss --without-pcap --without-sane --without-udev --without-unwind --without-usb --without-xfixes --without-xcomposite --without-xcursor --without-xinerama --without-xinput --without-xinput2 --without-xrandr --without-xrender --without-xshape --with-xshm --without-xxf86vm --without-wayland --without-pcsclite
       make
       
    - name: compile proton arm64ec
      run: |
       mkdir build
       cd build
       DEPS=/home/runner/work/wine/wine/imagefs/data/data/com.winlator.cmod/files/imagefs/usr ARCH="aarch64" WINARCH="arm64ec" ../build.sh --configure --build --compress
